run "index_html" {
  assert {
    condition = local_file.index_html.content == chomp(
      <<-EOT
      <!DOCTYPE html><html><body><h1>Hello, HTML.tf!</h1><p>This HTML was generated by <a href="https://registry.terraform.io/providers/koki-develop/html/latest/docs">HTML.tf</a>.</p></body></html>
      EOT
    )
    error_message = ""
  }
}
