resource "html_html" "main" {
  children = [html_body.main.html]
}

resource "html_body" "main" {
  children = [
    html_h1.heading.html,
    html_p.message.html,
  ]
}

resource "html_h1" "heading" {
  children = ["Hello, HTML.tf!"]
}

resource "html_p" "message" {
  children = ["This HTML is generated by ${html_a.html_tf.html}."]
}

resource "html_a" "html_tf" {
  href     = "https://registry.terraform.io/providers/koki-develop/html/latest/docs"
  children = ["HTML.tf"]
}

resource "local_file" "index_html" {
  filename = "index.html"
  content  = html_html.main.html
}
