name: Test

on: push

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go test -v ./...

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v6.5.0

  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.2
      - run: terraform fmt -recursive -check

  tf-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples:
          - data-sources
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.2
      - name: create terraformrc
        run: |
          cat <<EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "registry.terraform.io/koki-develop/html" = "$HOME/go/bin"
            }

            direct {}
          }
          EOF
      - run: go install
      - name: test
        working-directory: examples/${{ matrix.examples }}
        run: |
          for wd in $(ls -d */); do
            echo "::group::${wd}"
            cd $wd
            terraform init
            terraform test
            cd ..
            echo "::endgroup::"
          done
